### ISSUE TITLE
Retry conditions only trigger on AxiosError.

### ISSUE THREAD

**Issue by shtlrs** [softonic/axios-retry#229]
I'm consuming a specific API that returns internal codes in the responses.
Example:
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "message": "failure message",
  "errorCode": 752
}

```

The thing is, the HTTP request's status code is `200`, which means that `AxiosError` won't be thrown by the client, and thus, my retry condition won't trigger.

Is this something that:
1. Has a potential, not so ugly, workaround that can be done on my side ?
2. Something to be considered for the library, as we can't really guarantee that the consumed API will return erroneous status codes.

**Comment by nathanpovo** [comment]
You can pass a function of your choice to the `retryCondition` [option](https://github.com/softonic/axios-retry#options) that checks for error conditions that are specific to your system.

**Comment by yutak23** [comment]
If the status code is 2xx, then I don't think axios-retry is available.
The reason is that `axios-retry` implements an interceptor for non-2xx responses, as you can see in [the code](https://github.com/softonic/axios-retry/blob/master/es/index.mjs#L210)

The following is taken from [axios' README](https://github.com/axios/axios#interceptors)
```js
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response;
  }, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
    return Promise.reject(error);
  });
```

If you want to implement retry processing in 2xx, I think you need to implement the interceptor by yourself referring to the above instead of using `axios-retry`.

**Comment by nathanpovo** [comment]
Found a similar issue https://github.com/softonic/axios-retry/issues/100 which describes a way to implement a custom interceptor for 2xx responses.

**Comment by shtlrs** [comment]
Ok, I see the maintainers don't want to include this behavior since there are workarounds.

I'll be closing this then.

Thanks folks.
