### ISSUE TITLE
Probably error in `isNetworkError` function

### ISSUE THREAD

**Issue by 0FilipK** [softonic/axios-retry#65]
Hello,

I spend a while to debug why my app are not retry calls and I found that If caused by `isNetworkError` function. Function takes parameter `error` and checks:

```
!error.response &&
Boolean(error.code) && // Prevents retrying cancelled requests
error.code !== 'ECONNABORTED' && // Prevents retrying timed out requests
isRetryAllowed(error)
```

The problem is if you have 401 (Unauthorized) error the error.response looks like:

```
{
  "data": {},
  "status": 401,
  "statusText": "Unauthorized",
  "headers": {},
  "config": {},
  "request": {}
}
```

so first two conditions are not true. Response does exist and error.code is not Boolean (it's undefined actually). The next two "checks" are true, error.code is not `ECONNABORTED` and it's not blacklisted by `isRetryAllowed`:
```
error.code !== 'ECONNABORTED' &&
isRetryAllowed(error)
```

Maybe I'm doing something wrong or this is bug? I know I can pass my own function to check if that should update but it should work in that case anyway.

**Comment by sonniimukh** [comment]
I don't think that `401` is actually a network error. You sent request and received a response. Thus, the network layer works just fine. You probably need to handle authorization in other middleware.

Having that said, there seems to be a real error in this function/logic.

The use case I've been working on recently is a front end that periodically checks the status updates from the API by doing repetitive GET requests. When API server goes down we'd like retrying a few times. This also covers network partitioning cases, etc. So, I believe timeout connecting to the server is a network error by it's nature.

The problem is that when connection timeout happens there's neither `code` nor `response` in the `error`. And because of this `ECONNABORTED` check the function returns false.

I would like to suggest adjusting the logic here as follows:
```javascript
export function isNetworkError(error) {
  return (
    !error.response &&
    isRetryAllowed(error) && // Prevents retrying unsafe errors
    !(Boolean(error.code) && error.code == 'ECONNABORTED') // Prevents retrying timed out requests
  );
}
```

Not sure about the `// Prevents retrying cancelled requests` logic, though.

**Comment by mindhells** [comment]
you can easily set you `retryCondition` using this library API as described in the README
